### ISSUE TITLE
Add support for consuming data.yml

### ISSUE THREAD

**Issue by saifulislampi** [floability/floability-cli#11]
If `data.yml` is provided `flobility fetch` should download data in specified location. And `floability run` should check the specified location before running, if data is not already downloaded it should do a fetch.

**Comment by saifulislampi** [comment]
@dthain we can discuss data.yml specs here. For starter I am thinking something like this

```
# data.yml
data:
  - name: training_set
    source_type: url
    source: https://example.com/data/training_set.zip
    verification:
      checksum: abc123
    target_location: /data/training_set

  - name: input_images
    source_type: filesystem
    source: *.crc.nd.eddu:/data/crc_shared/experiment/input_images
    verification:
      checksum: def456
    target_location: /data/input_images

  - name: model_weights
    source_type: backpack
    source: /path/inside/backpack
```
